# Generated by Django 2.2.7 on 2019-11-15 14:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('segment', wagtail.core.blocks.StructBlock([('extra_klasses', wagtail.core.blocks.CharBlock(help_text='semantic ui classes (eg: raised ...', required=False)), ('name', wagtail.core.blocks.CharBlock(help_text='sets an anchor text id. Can leave blank', required=False)), ('header', wagtail.core.blocks.RichTextBlock(help_text='Can leave blank', required=False)), ('content', wagtail.core.blocks.RichTextBlock(help_text='template tags are available eg: {{ user }} , {{ last_login }}, {{ now }}, {{ today }} {{request }}', required=False)), ('divider', wagtail.core.blocks.BooleanBlock(required=False)), ('boxed', wagtail.core.blocks.BooleanBlock(required=False)), ('published', wagtail.core.blocks.BooleanBlock(default=True, required=False))], classname='segment')), ('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('two_columns', wagtail.core.blocks.StructBlock([('left_column', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('segment', wagtail.core.blocks.StructBlock([('extra_klasses', wagtail.core.blocks.CharBlock(help_text='semantic ui classes (eg: raised ...', required=False)), ('name', wagtail.core.blocks.CharBlock(help_text='sets an anchor text id. Can leave blank', required=False)), ('header', wagtail.core.blocks.RichTextBlock(help_text='Can leave blank', required=False)), ('content', wagtail.core.blocks.RichTextBlock(help_text='template tags are available eg: {{ user }} , {{ last_login }}, {{ now }}, {{ today }} {{request }}', required=False)), ('divider', wagtail.core.blocks.BooleanBlock(required=False)), ('boxed', wagtail.core.blocks.BooleanBlock(required=False)), ('published', wagtail.core.blocks.BooleanBlock(default=True, required=False))]))], icon='arrow-right', label='Left column content')), ('right_column', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('segment', wagtail.core.blocks.StructBlock([('extra_klasses', wagtail.core.blocks.CharBlock(help_text='semantic ui classes (eg: raised ...', required=False)), ('name', wagtail.core.blocks.CharBlock(help_text='sets an anchor text id. Can leave blank', required=False)), ('header', wagtail.core.blocks.RichTextBlock(help_text='Can leave blank', required=False)), ('content', wagtail.core.blocks.RichTextBlock(help_text='template tags are available eg: {{ user }} , {{ last_login }}, {{ now }}, {{ today }} {{request }}', required=False)), ('divider', wagtail.core.blocks.BooleanBlock(required=False)), ('boxed', wagtail.core.blocks.BooleanBlock(required=False)), ('published', wagtail.core.blocks.BooleanBlock(default=True, required=False))]))], icon='arrow-right', label='Right column content')), ('boxed', wagtail.core.blocks.BooleanBlock(required=False)), ('extra_klasses', wagtail.core.blocks.CharBlock(help_text='semantic ui classes (eg: raised ...', required=False)), ('template', wagtail.core.blocks.ChoiceBlock(choices=[('cms/blocks/even_column_block.html', '2 even Col'), ('cms/blocks/big_right_column_block.html', 'Big right'), ('cms/blocks/big_left_column_block.html', 'Big left')]))])), ('embedded_video', wagtail.embeds.blocks.EmbedBlock(icon='media'))], blank=True, null=True),
        ),
    ]
