# Generated by Django 2.2.7 on 2019-11-19 22:16

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('segment', wagtail.core.blocks.StructBlock([('extra_klasses', wagtail.core.blocks.CharBlock(help_text='semantic ui classes (eg: raised ...', required=False)), ('header', wagtail.core.blocks.RichTextBlock(help_text='Can leave blank', required=False)), ('content', wagtail.core.blocks.RichTextBlock(help_text='template tags are available eg: {{ user }} , {{ last_login }}, {{ now }}, {{ today }} {{request }}', required=False)), ('divider', wagtail.core.blocks.BooleanBlock(required=False)), ('boxed', wagtail.core.blocks.BooleanBlock(required=False))], classname='segment')), ('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('two_columns', wagtail.core.blocks.StructBlock([('left_column', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('segment', wagtail.core.blocks.StructBlock([('extra_klasses', wagtail.core.blocks.CharBlock(help_text='semantic ui classes (eg: raised ...', required=False)), ('header', wagtail.core.blocks.RichTextBlock(help_text='Can leave blank', required=False)), ('content', wagtail.core.blocks.RichTextBlock(help_text='template tags are available eg: {{ user }} , {{ last_login }}, {{ now }}, {{ today }} {{request }}', required=False)), ('divider', wagtail.core.blocks.BooleanBlock(required=False)), ('boxed', wagtail.core.blocks.BooleanBlock(required=False))])), ('embedded_video', wagtail.embeds.blocks.EmbedBlock(icon='media')), ('button', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text='button label', required=False)), ('klass', wagtail.core.blocks.CharBlock(help_text='button colour', required=False)), ('url', wagtail.core.blocks.URLBlock(icon='arrow-right', required=False))], icon='button'))], icon='arrow-right', label='Left column content')), ('right_column', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('segment', wagtail.core.blocks.StructBlock([('extra_klasses', wagtail.core.blocks.CharBlock(help_text='semantic ui classes (eg: raised ...', required=False)), ('header', wagtail.core.blocks.RichTextBlock(help_text='Can leave blank', required=False)), ('content', wagtail.core.blocks.RichTextBlock(help_text='template tags are available eg: {{ user }} , {{ last_login }}, {{ now }}, {{ today }} {{request }}', required=False)), ('divider', wagtail.core.blocks.BooleanBlock(required=False)), ('boxed', wagtail.core.blocks.BooleanBlock(required=False))])), ('embedded_video', wagtail.embeds.blocks.EmbedBlock(icon='media')), ('button', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text='button label', required=False)), ('klass', wagtail.core.blocks.CharBlock(help_text='button colour', required=False)), ('url', wagtail.core.blocks.URLBlock(icon='arrow-right', required=False))], icon='button'))], icon='arrow-right', label='Right column content')), ('boxed', wagtail.core.blocks.BooleanBlock(required=False)), ('extra_klasses', wagtail.core.blocks.CharBlock(required=False))])), ('embedded_video', wagtail.embeds.blocks.EmbedBlock(icon='media')), ('button', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text='button label', required=False)), ('klass', wagtail.core.blocks.CharBlock(help_text='button colour', required=False)), ('url', wagtail.core.blocks.URLBlock(icon='arrow-right', required=False))], icon='button'))], blank=True, null=True),
        ),
    ]
